name = "FeynGen"
uuid = "7af2ec28-642b-4e53-bc5c-f6c5f969e857"
authors = ["Junyi Xiang"]
version = "0.1.1-DEV"

[deps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[compat]
Symbolics = "6.22.0"
TestItemRunner = "1.0.5"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
